name: Build and Deploy to tempvi.github.io (gh-pages)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the Angular project
      run: npm run build --prod

    - name: Deploy to tempvi.github.io (gh-pages branch)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_IO_TOKEN }}
        external_repository: tempvi/tempvi.github.io
        publish_branch: gh-pages
        publish_dir: dist/tempviweb/browser
